# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_answer_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(default=0)),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
