# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekka', '0005_answervotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_time',
            field=models.DateTimeField(default='2017-4-17T09:21:31+0000'),
        ),
    ]
