# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekka', '0006_auto_20160325_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
